[hugoVersion]
extended = true
min = "0.56.0"

[[mounts]]
source = "layouts"
target = "layouts"

[[imports]]
path = "github.com/dnb-org/dnb-hugo-functions"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/dnb-org/dnb-hugo-debug"
disable = false
ignoreConfig = false
ignoreImports = false
