[hugoVersion]
extended = true
min = "0.56.0"

[[mounts]]
source = "layouts"
target = "layouts"

[[imports]]
path = "github.com/dnb-org/components/functions"
disable = false
ignoreConfig = false
ignoreImports = false

[[imports]]
path = "github.com/dnb-org/debug"
disable = false
ignoreConfig = false
ignoreImports = false
