[module.hugoVersion]
extended = true
min = "0.82.0"

[[module.mounts]]
source = "layouts"
target = "layouts"

[params]
[params.dnb]
[params.dnb.hooks]
[params.dnb.hooks.config]
hooklink = "https://github.com/dnb-hugo/hooks/"
verbosity = 5
