[module.hugoVersion]
extended = true
min = "0.82.0"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.imports]]
path = "github.com/dnb-hugo/components/functions"
disable = false
ignoreConfig = false
ignoreImports = false

[params]
[params.dnb]
[params.dnb.hooks]
[params.dnb.hooks.config]
hooklink = "https://q.dnb9.xyz/hooks"
verbosity = 5
