[module.hugoVersion]
extended = true
min = "0.84.0"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "data"
target = "data"

[[module.mounts]]
source = "data/dnb/hooks"
target = "data/dnb/hooks"

[[module.imports]]
path = "github.com/dnb-hugo/components/functions"
disable = false
ignoreConfig = false
ignoreImports = false
